os: osx
osx_image: xcode11.3
language: go

branches:
 except:
   - main

git:
  depth: false
  quiet: true

go:
  - "1.14.x"

services:
  - docker

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew

before_cache:
  - brew cleanup
  - find /usr/local/Homebrew \! -regex ".+\.git.+" -delete

addons:
  homebrew:
    update: true
    packages:
      - gtk+3
      - adwaita-icon-theme
      - hicolor-icon-theme
      - shared-mime-info
      - create-dmg
      - fileicon
      - gtk-mac-integration
      - graphicsmagick
      - imagemagick
      - node

before_install:
  - "export DISPLAY=:99.0"
  - npm install --global create-dmg

install: make -C ci/ deps
script:
  - ls -alF /usr/local/bin
  - make -C ci/ clean-mac-bundle
  - make build-gui
  - make -C ci/ mac-bundle
  - make -C ci/ release-dmg
  - make -C ci/ release-gui

deploy:
  provider: releases
  api_key: $GH_DEPLOY_TOKEN
  file_glob: true
  file: release/*
  skip_cleanup: true
  on:
    tags: true
