os: osx
osx_image: xcode11.3
language: go

branches:
 except:
   - main

git:
  depth: false
  quiet: true

go:
  - "1.14.x"

services:
  - docker

addons:
  homebrew:
    update: true
    packages:
      - gtk+3
      - adwaita-icon-theme
      - hicolor-icon-theme
      - shared-mime-info
      - create-dmg
      - fileicon
      - gtk-mac-integration

before_install:
  - "export DISPLAY=:99.0"
install: travis_wait make -C ci/ deps
script:
  - travis_wait make -C ci/ clean-mac-bundle
  - travis_wait make build-gui
  - travis_wait make -C ci/ mac-bundle
  - travis_wait make -C ci/ release-dmg
  - travis_wait make -C ci/ release-gui

deploy:
  provider: releases
  api_key: $GH_DEPLOY_TOKEN
  file_glob: true
  file: release/*
  skip_cleanup: true
  on:
    tags: true
