os: osx
osx_image: xcode11.3
language: go

env:
  CACHE_NAME: all_caches

branches:
 except:
   - main

git:
  depth: false
  quiet: true

go:
  - "1.14.x"

services:
  - docker

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew

before_cache:
  - brew cleanup
  - find /usr/local/Homebrew \! -regex ".+\.git.+" -delete

before_install:
  - brew uninstall --ignore-dependencies --force java
  - brew uninstall --ignore-dependencies --force openjdk
  - travis_wait 40 brew update
  - brew install gtk+3 adwaita-icon-theme hicolor-icon-theme gnome-icon-theme shared-mime-info fileicon gtk-mac-integration
  - "export DISPLAY=:99.0"
  - npm install --global appdmg

install: make -C ci/ deps
script:
  - make -C ci/ clean-mac-bundle
  - make build-gui
  - make -C ci/ make-mac-bundle
  - make -C ci/ make-dmg
  - make -C ci/ make-gui-for-release

deploy:
  provider: releases
  api_key: $GH_DEPLOY_TOKEN
  file_glob: true
  file: release/*
  skip_cleanup: true
  on:
    tags: true
