name: CoyIM Linux CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        go: [ '1.14', '1.13' , '1.12', '1.11' ]

    name: CoyIM go-${{ matrix.go }} test
    steps:
      - name: install dependencies
        run: sudo apt-get install libgtk-3-dev gettext libglib2.0-dev libc6-dev-i386 xvfb
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go version
