name: CoyIM CI Mac

on: [push]

jobs:
  build-release-osx:
    name: Build release test (OS X)
    runs-on: macos-10.15

    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
      - name: install OS dependencies
        run: brew install gtk+3 adwaita-icon-theme hicolor-icon-theme shared-mime-info fileicon
      - name: install DMG dependencies
        run: npm install --global appdmg
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: install project dependencies
        run: make -C ci/ deps
      - name: build release
        run: |
          make -C ci/ clean-mac-bundle
          make build-gui
          make -C ci/ make-mac-bundle
          make -C ci/ make-dmg
          make -C ci/ make-gui-for-release

  
