name: CoyIM CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
        
    strategy:
      matrix:
        go: [ '1.15', '1.14', '1.13', '1.12', '1.11' ]
        os: [ ubuntu-16.04, macos-latest ]

        include:
        - os: ubuntu-16.04
          INSTALL_DEPS: sudo apt-get install libgtk-3-dev gettext libglib2.0-dev libc6-dev-i386 xvfb
        - os: macos-latest
          INSTALL_DEPS: brew install gtk+3 adwaita-icon-theme hicolor-icon-theme shared-mime-info gtk-mac-integration create-dmg fileicon

        # We only want to run Golang 1.14 on OS X
        exclude:
        - os: macos-latest
          go: '1.15'
        - os: macos-latest
          go: '1.13'
        - os: macos-latest
          go: '1.12'
        - os: macos-latest
          go: '1.11'

    name: CoyIM go-${{ matrix.go }} test (${{ matrix.os }})
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}        
      - name: install OS dependencies
        run: ${{ matrix.INSTALL_DEPS }}
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: install project dependencies
        run: make -C ci/ deps
        env:
          DISPLAY: ':99.0'
      - name: run tests
        run: make -C ci/
        env:
          DISPLAY: ':99.0'

  notify:
    name: Notify on success or failure
    needs: test
    runs-on: ubuntu-20.04
    if: always() # set always
    steps:
      - uses: technote-space/workflow-conclusion-action@v1
      - name: send message on success
        if: ${{ env.WORKFLOW_CONCLUSION == 'success' }}
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ secrets.MATRIX_COYIM_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          server: ${{ secrets.MATRIX_SERVER }}
          message: <h1><span data-mx-color="#00FF2D">SUCCESS</span></h1> Build <a href="https://github.com/${{github.repository}}/actions/runs/${{github.run_number}}">${{github.repository}} \#${{github.run_number}} ${{github.workflow}}</a> was successful!<br> triggered by <a href="https://github.com/${{github.actor}}">${{github.actor}}</a>
      - name: send message on failure
        if: ${{ env.WORKFLOW_CONCLUSION == 'failure' }}
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ secrets.MATRIX_COYIM_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          server: ${{ secrets.MATRIX_SERVER }}
          message: <h1><span data-mx-color="#FF0A00>FAILURE</span></h1> Build <a href="https://github.com/${{github.repository}}/actions/runs/${{github.run_number}}">${{github.repository}} \#${{github.run_number}} ${{github.workflow}}</a> failed!<br> triggered by <a href="https://github.com/${{github.actor}}">${{github.actor}}</a>
      - name: send message on cancelled
        if: ${{ env.WORKFLOW_CONCLUSION == 'cancelled' }}
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ secrets.MATRIX_COYIM_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          server: ${{ secrets.MATRIX_SERVER }}
          message: <h1><span data-mx-color="#FFF608>CANCELLED</span></h1> Build <a href="https://github.com/${{github.repository}}/actions/runs/${{github.run_number}}">${{github.repository}} \#${{github.run_number}} ${{github.workflow}}</a> was cancelled!<br> triggered by <a href="https://github.com/${{github.actor}}">${{github.actor}}</a>


# we need a release job for linux, with RELEASE=true
