name: verify
on: push
jobs:
  verify:
    runs-on: ubuntu-20.04
    steps:
      - name: send message
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ secrets.MATRIX_COYIM_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          server: ${{ secrets.MATRIX_SERVER }}
          message: >
            <h1><span data-mx-color="#00FF2D">SUCCESS</span></h1>
            Build <a href="${{GITHUB_SERVER_URL}}/${{GITHUB_REPOSITORY}}/actions/runs/${{GITHUB_RUN_NUMBER}}">
            ${{GITHUB_REPOSITORY}} #${{GITHUB_RUN_NUMBER}} ${{GITHUB_WORKFLOW}}</a> was successful!<br>
            triggered by <a href="${{GITHUB_SERVER_URL}}/${{GITHUB_ACTOR}}">${{GITHUB_ACTOR}}</a>
          
